let casterToken = canvas.tokens.get(args[0].tokenId);

new Sequence()
.effect()
    .file('jb2a.magic_signs.circle.02.illusion.intro.yellow')
    .atLocation(casterToken)
    .scaleToObject(1.4)
    .belowTokens()
    .fadeIn(500)
    .fadeOut(500)
    .duration(3000)
    .filter("Glow", { color: 0xFFA500 })
    .waitUntilFinished(-2500)
.effect()
    .from(casterToken)
    .duration(2500)
    .fadeIn(500)
    .fadeOut(500)
    .atLocation(casterToken)
    .filter("Glow", { color: 0xFFA500 })
    .scaleToObject()
    .waitUntilFinished(-500)
.effect()
    .file('jb2a.swirling_leaves.outburst.01.orangered')
    .atLocation(casterToken)
    .scale(1)
    .fadeIn(500)
    .fadeOut(500)
    .duration(2000)
.play()