let casterToken = canvas.tokens.get("CG0UrCKu8gh2MaW9");
let target = game.user.targets.first();

new Sequence()
    .effect()
        .file("jb2a.extras.tmfx.runes.circle.outpulse.evocation")
        .atLocation(casterToken)
        .duration(2000)
        .fadeIn(500)
        .fadeOut(500)
        .scale(0.5)
        .waitUntilFinished(-1200)
        .filter("Glow", { color: 0xffa500 })
        .opacity(0.8)
    .effect()
        .file("jb2a.spear.melee.fire.orange")
        .atLocation(casterToken)
        .stretchTo(target)
        .waitUntilFinished(-1200)
        .fadeIn(500)
        .fadeOut(1500)
    .effect()
        .file("jb2a.explosion.02.orange")
        .atLocation(target)
        .fadeIn(100)
        .fadeOut(100)
        .scale(0.5)
    .effect()
        .file("jb2a.flaming_sphere.200px.orange.02")
        .scaleToObject(2)
        .belowTokens()
        .attachTo(target)
        .duration(2000)
        .fadeIn(500)
        .fadeOut(1000)
        .persist()
        .name(`searing-smite-${target.id}`)
    .play()